import type { Lang } from "@/i18n/translations";

type Dict = Record<string, string>;

const EN: Dict = {
  step_of: "Step {n} of {total}",
  back: "Back",
  continue: "Continue",
  save_exit: "Save & exit",
  generating: "Writing your CV with AI…",
  s1_title: "What's your name?",
  s1_sub: "Use the name you want on the CV.",
  s1_name: "Full name",
  s1_headline: "Target role / headline",
  s1_headline_ph: "e.g. Senior Project Engineer",
  s2_title: "How can employers reach you?",
  s2_email: "Email",
  s2_phone: "Phone (with country code)",
  s2_city: "City",
  s2_nat: "Nationality (optional)",
  s2_civil: "Civil status (optional)",
  civil_single: "Single",
  civil_married: "Married",
  civil_divorced: "Divorced",
  civil_prefer: "Prefer not to say",
  s3_title: "Tell us about yourself.",
  s3_sub: "1–2 sentences. Plain words are fine — AI will polish it.",
  s3_ph: "I'm an engineer with 6 years in oil & gas logistics across Basra…",
  s4_title: "Work experience",
  s4_sub: "Add every job that matters. AI will turn raw notes into impact bullets.",
  s4_role: "Job title",
  s4_company: "Company",
  s4_dates: "Dates (e.g. 2019 – Present)",
  s4_desc: "What did you do? (raw notes are fine)",
  s4_add: "+ Add another job",
  s4_remove: "Remove",
  s5_title: "Education",
  s5_degree: "Degree / certificate",
  s5_school: "School / university",
  s5_dates: "Dates",
  s5_add: "+ Add education",
  s6_title: "Skills",
  s6_sub: "Press Enter after each skill.",
  s6_ph: "Project management",
  s7_title: "Languages",
  s7_sub: "Add your languages and proficiency.",
  s7_name: "Language",
  s7_level: "Level",
  lvl_native: "Native",
  lvl_pro: "Professional",
  lvl_conv: "Conversational",
  lvl_basic: "Basic",
  s7_add: "+ Add language",
  s8_title: "Review your answers",
  s8_sub: "Looks good? Pick a design next.",
  s8_continue: "Pick design →",
  design_title: "Choose your CV design",
  design_sub: "All templates are ATS-friendly and print-ready.",
  langs_title: "Pick languages for your CV",
  langs_sub: "Pick 1, 2, or 3 languages. AI will write your CV in each one.",
  generate_btn: "Generate with AI →",
  preview_title: "Your CV",
  preview_regen: "Regenerate",
  preview_edit: "Edit answers",
  preview_download: "Download PDF",
  preview_empty: "Nothing generated yet.",
  toast_saved: "Saved.",
  toast_generated: "Your CV is ready.",
  pick_at_least_one: "Pick at least 1 language.",
  field_required: "This field is required.",
};

const KU: Dict = {
  step_of: "هەنگاوی {n} لە {total}",
  back: "گەڕانەوە",
  continue: "بەردەوام بە",
  save_exit: "پاشەکەوت و دەرچوون",
  generating: "بە AI سی‌ڤیەکەت دەنووسرێت…",
  s1_title: "ناوت چییە؟",
  s1_sub: "ئەو ناوە بنووسە کە دەتەوێت لە سی‌ڤی بێت.",
  s1_name: "ناوی تەواو",
  s1_headline: "پۆستی مەبەست",
  s1_headline_ph: "نموونە: ئەندازیاری پڕۆژەی باڵا",
  s2_title: "چۆن کارفەرما پەیوەندیت پێوە بکات؟",
  s2_email: "ئیمەیڵ",
  s2_phone: "تەلەفۆن (لەگەڵ کۆدی وڵات)",
  s2_city: "شار",
  s2_nat: "ڕەگەزنامە (ئیختیاری)",
  s2_civil: "بارودۆخی هاوسەرگیری (ئیختیاری)",
  civil_single: "تاک",
  civil_married: "هاوسەردار",
  civil_divorced: "جیابووەوە",
  civil_prefer: "نامەوێت بڵێم",
  s3_title: "باسی خۆت بکە.",
  s3_sub: "١-٢ ڕستە. ووشە سادە باشە — AI ڕێکی دەخات.",
  s3_ph: "من ئەندازیارم بە ٦ ساڵ ئەزموون لە لۆجستی نەوت و گاز…",
  s4_title: "ئەزموونی کار",
  s4_sub: "هەموو ئەو کارانە زیاد بکە کە گرنگن. AI تێبینییەکانت دەکات بە خاڵی کاریگەر.",
  s4_role: "پۆست",
  s4_company: "کۆمپانیا",
  s4_dates: "بەروار (نموونە: ٢٠١٩ – ئێستا)",
  s4_desc: "چیت کردووە؟ (تێبینی سادە باشە)",
  s4_add: "+ کارێکی تر زیاد بکە",
  s4_remove: "سڕینەوە",
  s5_title: "خوێندن",
  s5_degree: "بڕوانامە",
  s5_school: "زانکۆ / قوتابخانە",
  s5_dates: "بەروار",
  s5_add: "+ خوێندن زیاد بکە",
  s6_title: "لێهاتوویەکان",
  s6_sub: "دوای هەر یەکێک Enter دابگرە.",
  s6_ph: "بەڕێوەبردنی پڕۆژە",
  s7_title: "زمانەکان",
  s7_sub: "زمانەکانت و ئاستەکانیان زیاد بکە.",
  s7_name: "زمان",
  s7_level: "ئاست",
  lvl_native: "زمانی دایک",
  lvl_pro: "پیشەیی",
  lvl_conv: "گفتوگۆ",
  lvl_basic: "بنەڕەتی",
  s7_add: "+ زمان زیاد بکە",
  s8_title: "وەڵامەکانت ببینەوە",
  s8_sub: "باشە؟ ئێستا دیزاینێک هەڵبژێرە.",
  s8_continue: "هەڵبژاردنی دیزاین →",
  design_title: "دیزاینی سی‌ڤیەکەت هەڵبژێرە",
  design_sub: "هەموو نموونەکان گونجاون بۆ ATS و ئامادەن بۆ چاپ.",
  langs_title: "زمانەکانی سی‌ڤیەکەت هەڵبژێرە",
  langs_sub: "١، ٢، یان ٣ زمان هەڵبژێرە. AI بە هەریەکەیان دەنووسێت.",
  generate_btn: "بە AI دروستی بکە →",
  preview_title: "سی‌ڤی تۆ",
  preview_regen: "دروستکردنەوە",
  preview_edit: "دەستکاری وەڵامەکان",
  preview_download: "داگرتنی PDF",
  preview_empty: "هێشتا هیچ دروست نەکراوە.",
  toast_saved: "پاشەکەوت کرا.",
  toast_generated: "سی‌ڤیەکەت ئامادەیە.",
  pick_at_least_one: "لانی کەم ١ زمان هەڵبژێرە.",
  field_required: "ئەم خانە پێویستە.",
};

const AR: Dict = {
  step_of: "الخطوة {n} من {total}",
  back: "رجوع",
  continue: "متابعة",
  save_exit: "حفظ وخروج",
  generating: "يكتب الذكاء الاصطناعي سيرتك…",
  s1_title: "ما اسمك؟",
  s1_sub: "اكتب الاسم الذي تريده على السيرة.",
  s1_name: "الاسم الكامل",
  s1_headline: "المسمى الوظيفي المستهدف",
  s1_headline_ph: "مثال: مهندس مشاريع أول",
  s2_title: "كيف يتواصل معك أصحاب العمل؟",
  s2_email: "البريد الإلكتروني",
  s2_phone: "الهاتف (مع رمز الدولة)",
  s2_city: "المدينة",
  s2_nat: "الجنسية (اختياري)",
  s2_civil: "الحالة المدنية (اختياري)",
  civil_single: "أعزب",
  civil_married: "متزوج",
  civil_divorced: "مطلق",
  civil_prefer: "أفضل عدم الإفصاح",
  s3_title: "حدّثنا عن نفسك.",
  s3_sub: "جملة أو اثنتان. الكلمات البسيطة كافية — سيُحسّنها الذكاء الاصطناعي.",
  s3_ph: "أنا مهندس بخبرة ٦ سنوات في لوجستيات النفط والغاز…",
  s4_title: "الخبرة المهنية",
  s4_sub: "أضف كل وظيفة مهمة. سيحوّل الذكاء الاصطناعي ملاحظاتك إلى نقاط أثر.",
  s4_role: "المسمى الوظيفي",
  s4_company: "الشركة",
  s4_dates: "التواريخ (مثال: ٢٠١٩ – حتى الآن)",
  s4_desc: "ماذا فعلت؟ (ملاحظات بسيطة كافية)",
  s4_add: "+ إضافة وظيفة أخرى",
  s4_remove: "إزالة",
  s5_title: "التعليم",
  s5_degree: "الشهادة",
  s5_school: "الجامعة / المدرسة",
  s5_dates: "التواريخ",
  s5_add: "+ إضافة تعليم",
  s6_title: "المهارات",
  s6_sub: "اضغط Enter بعد كل مهارة.",
  s6_ph: "إدارة المشاريع",
  s7_title: "اللغات",
  s7_sub: "أضف لغاتك ومستوى إتقانك.",
  s7_name: "اللغة",
  s7_level: "المستوى",
  lvl_native: "اللغة الأم",
  lvl_pro: "احترافي",
  lvl_conv: "محادثة",
  lvl_basic: "أساسي",
  s7_add: "+ إضافة لغة",
  s8_title: "راجع إجاباتك",
  s8_sub: "تبدو رائعة؟ اختر التصميم الآن.",
  s8_continue: "اختر التصميم →",
  design_title: "اختر تصميم سيرتك الذاتية",
  design_sub: "جميع القوالب متوافقة مع ATS وجاهزة للطباعة.",
  langs_title: "اختر لغات سيرتك",
  langs_sub: "اختر لغة أو لغتين أو ثلاث. سيكتب الذكاء الاصطناعي سيرتك بكل لغة.",
  generate_btn: "إنشاء بالذكاء الاصطناعي →",
  preview_title: "سيرتك الذاتية",
  preview_regen: "إعادة الإنشاء",
  preview_edit: "تعديل الإجابات",
  preview_download: "تنزيل PDF",
  preview_empty: "لم يُنشأ شيء بعد.",
  toast_saved: "تم الحفظ.",
  toast_generated: "سيرتك جاهزة.",
  pick_at_least_one: "اختر لغة واحدة على الأقل.",
  field_required: "هذا الحقل مطلوب.",
};

const ALL: Record<Lang, Dict> = { en: EN, ku: KU, ar: AR };

export function w(lang: Lang, key: string, vars?: Record<string, string | number>) {
  const v = ALL[lang][key] ?? EN[key] ?? key;
  if (!vars) return v;
  return v.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
