/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvIdPreviewRouteImport } from './routes/_authenticated/cv.$id.preview'
import { Route as AuthenticatedCvIdDesignRouteImport } from './routes/_authenticated/cv.$id.design'
import { Route as AuthenticatedCvIdBuildRouteImport } from './routes/_authenticated/cv.$id.build'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvIdPreviewRoute =
  AuthenticatedCvIdPreviewRouteImport.update({
    id: '/cv/$id/preview',
    path: '/cv/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCvIdDesignRoute = AuthenticatedCvIdDesignRouteImport.update({
  id: '/cv/$id/design',
  path: '/cv/$id/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvIdBuildRoute = AuthenticatedCvIdBuildRouteImport.update({
  id: '/cv/$id/build',
  path: '/cv/$id/build',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cv/$id/build': typeof AuthenticatedCvIdBuildRoute
  '/cv/$id/design': typeof AuthenticatedCvIdDesignRoute
  '/cv/$id/preview': typeof AuthenticatedCvIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cv/$id/build': typeof AuthenticatedCvIdBuildRoute
  '/cv/$id/design': typeof AuthenticatedCvIdDesignRoute
  '/cv/$id/preview': typeof AuthenticatedCvIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/cv/$id/build': typeof AuthenticatedCvIdBuildRoute
  '/_authenticated/cv/$id/design': typeof AuthenticatedCvIdDesignRoute
  '/_authenticated/cv/$id/preview': typeof AuthenticatedCvIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/dashboard'
    | '/cv/$id/build'
    | '/cv/$id/design'
    | '/cv/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/dashboard'
    | '/cv/$id/build'
    | '/cv/$id/design'
    | '/cv/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/_authenticated/dashboard'
    | '/_authenticated/cv/$id/build'
    | '/_authenticated/cv/$id/design'
    | '/_authenticated/cv/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv/$id/preview': {
      id: '/_authenticated/cv/$id/preview'
      path: '/cv/$id/preview'
      fullPath: '/cv/$id/preview'
      preLoaderRoute: typeof AuthenticatedCvIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv/$id/design': {
      id: '/_authenticated/cv/$id/design'
      path: '/cv/$id/design'
      fullPath: '/cv/$id/design'
      preLoaderRoute: typeof AuthenticatedCvIdDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv/$id/build': {
      id: '/_authenticated/cv/$id/build'
      path: '/cv/$id/build'
      fullPath: '/cv/$id/build'
      preLoaderRoute: typeof AuthenticatedCvIdBuildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCvIdBuildRoute: typeof AuthenticatedCvIdBuildRoute
  AuthenticatedCvIdDesignRoute: typeof AuthenticatedCvIdDesignRoute
  AuthenticatedCvIdPreviewRoute: typeof AuthenticatedCvIdPreviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCvIdBuildRoute: AuthenticatedCvIdBuildRoute,
  AuthenticatedCvIdDesignRoute: AuthenticatedCvIdDesignRoute,
  AuthenticatedCvIdPreviewRoute: AuthenticatedCvIdPreviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
